# Generated by Django 2.2 on 2021-12-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211204_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='testproduct'),
            preserve_default=False,
        ),
    ]
